# Generated by Django 4.2.27 on 2026-01-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('local', models.CharField(blank=True, choices=[('SALNHA', 'Salinha'), ('CAMPO', 'Campo'), ('RANCHO', 'Rancho'), ('PRAÇA', 'Praça'), ('RU', 'RU'), ('OUTROS', 'Outros')], default='SALNHA', max_length=100, null=True)),
                ('competencia', models.CharField(max_length=50)),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='fotos_atividades')),
                ('tempo_atividade', models.PositiveIntegerField(blank=True, help_text='Tempo da atividade em minutos', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PAC', 'Pacote'), ('CX', 'Caixa'), ('TUBO', 'Tubo'), ('METRO', 'Metro'), ('L', 'Litro'), ('KG', 'Quilo'), ('OUTROS', 'Outros')], default='UN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Semanario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(blank=True, max_length=100, null=True)),
                ('sala', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz')], max_length=20)),
                ('projetor', models.BooleanField(default=True)),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanarios', to='sabado.sabado')),
            ],
        ),
    ]
