# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semanario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanario',
            name='talentos_necessarios',
            field=models.ManyToManyField(blank=True, to='voluntario.talento'),
        ),
        migrations.AddField(
            model_name='material',
            name='atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='semanario.atividade'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atividade',
            name='semanario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='semanario.semanario'),
        ),
        migrations.AddConstraint(
            model_name='semanario',
            constraint=models.UniqueConstraint(fields=('data', 'sala'), name='uniq_semanario_por_sabado_sala'),
        ),
    ]
