# Generated by Django 4.2.27 on 2026-01-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='titulo',
            new_name='atividade',
        ),
    ]
