# Generated by Django 4.2.27 on 2026-04-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo_local',
            field=models.CharField(blank=True, choices=[('MERCADO', 'Mercado'), ('PAPELARIA', 'Papelaria'), ('SALINHA', 'Salinha'), ('ARTIGO DE FESTA', 'Artigo de Festa'), ('OUTROS', 'Outros')], max_length=100, null=True),
        ),
    ]
