# Generated by Django 4.2.27 on 2026-07-18 22:59

from django.db import migrations, models
import django.db.models.deletion


def migrar_locais_materiais(apps, schema_editor):
    Local = apps.get_model('supply', 'Local')
    Material = apps.get_model('semanario', 'Material')
    tipos = {
        'MERCADO': 'MERCADO',
        'PAPELARIA': 'PAPELARIA',
        'ARTIGO DE FESTA': 'ARTIGOS_FESTA',
        'OUTROS': 'OUTROS',
        'SALINHA': 'OUTROS',
    }
    rotulos = {
        'MERCADO': 'Mercado', 'PAPELARIA': 'Papelaria',
        'ARTIGO DE FESTA': 'Artigos de festa', 'OUTROS': 'Outros',
        'SALINHA': 'Salinha',
    }
    for material in Material.objects.exclude(local_compra__isnull=True).exclude(local_compra='') | Material.objects.exclude(tipo_local__isnull=True).exclude(tipo_local=''):
        nome = (material.local_compra or rotulos.get(material.tipo_local) or 'Local não informado').strip()
        tipo = tipos.get(material.tipo_local, 'OUTROS')
        local, _ = Local.objects.get_or_create(nome=nome, tipo=tipo)
        material.local_id = local.id
        material.save(update_fields=['local'])


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_local_remove_pedido_local_compra_and_more'),
        ('semanario', '0003_alter_material_tipo_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='supply.local'),
        ),
        migrations.RunPython(migrar_locais_materiais, migrations.RunPython.noop),
        migrations.RemoveField(model_name='material', name='local_compra'),
        migrations.RemoveField(model_name='material', name='tipo_local'),
    ]
