# Generated by Django 4.2.27 on 2026-01-18 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0003_alter_semanario_projetor_alter_semanario_vagas'),
    ]

    operations = [
        migrations.AddField(
            model_name='semanario',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
