# Generated by Django 4.2.27 on 2026-01-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0004_semanario_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semanario',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
