# Generated by Django 4.2.27 on 2026-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0006_alter_atividade_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='dimensao_competencia',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
