# Generated by Django 4.2.27 on 2026-07-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0006_material_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='competencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
