# Generated by Django 4.2.27 on 2026-07-24 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semanario', '0007_alter_atividade_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='especificar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='material',
            name='requisitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais_requisitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
