# Generated by Django 4.2.27 on 2026-01-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0007_atividade_dimensao_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dimensao_competencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, choices=[('SALINHA', 'Salinha'), ('FF', 'FF'), ('CAMPO', 'Campo'), ('RANCHO', 'Rancho'), ('PRAÇA', 'Praça'), ('RU', 'RU'), ('OUTROS', 'Outros')], default='SALINHA', max_length=100, null=True),
        ),
    ]
