# Generated by Django 4.2.27 on 2026-08-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0008_material_especificar_material_requisitado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='unidade',
        ),
    ]
