# Generated by Django 4.2.27 on 2026-01-24 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0009_alter_atividade_dimensao_competencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='dimensao_competencia',
        ),
    ]
