# Generated by Django 4.2.27 on 2026-02-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0011_atividade_dimensao_competencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='dimensao_competencia',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
