# Generated by Django 4.2.27 on 2026-02-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semanario', '0012_alter_atividade_dimensao_competencia'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='semanario',
            constraint=models.UniqueConstraint(fields=('data', 'sala'), name='uniq_semanario_por_sabado_sala'),
        ),
    ]
