# Generated by Django 4.2.27 on 2026-07-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_pcf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackarea',
            name='dor_geral',
            field=models.TextField(blank=True, help_text='Dores do PCF em geral', null=True),
        ),
        migrations.AddField(
            model_name='feedbackarea',
            name='sugestao',
            field=models.TextField(blank=True, help_text='Sugestões de projetos', null=True),
        ),
        migrations.AlterField(
            model_name='feedbackarea',
            name='descricao',
            field=models.TextField(blank=True, help_text='Dores da sua área', null=True),
        ),
    ]
