# Generated by Django 4.2.27 on 2026-08-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_pcf', '0003_alter_feedbackarea_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackarea',
            name='area',
            field=models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30),
        ),
    ]
