# Generated by Django 4.2.27 on 2026-08-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_conta_evento_lancamento_area_tetoarea_recargacartao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_pcf', '0004_alter_feedbackarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoreembolso',
            name='area',
            field=models.CharField(blank=True, choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30, verbose_name='área'),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, help_text='Comprovante de que o ADM pagou.', upload_to='reembolsos_pagos/'),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='conta_pagamento',
            field=models.ForeignKey(blank=True, help_text='De onde saiu o pagamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_pagos', to='adm.conta'),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos', to='adm.evento'),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='pago_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='pago_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_pagos_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoreembolso',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('PAGO', 'Pago'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=15),
        ),
    ]
