# Generated by Django 4.2.27 on 2026-09-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_pcf', '0006_area_dos_pedidos_ja_na_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoreembolso',
            name='comprovante',
            field=models.FileField(blank=True, help_text='Opcional. Quem decide se o pedido vale sem comprovante é a ADM/Fin, na hora de aprovar.', upload_to='reembolsos/'),
        ),
    ]
