# Generated by Django 4.2.27 on 2026-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_pcf', '0007_alter_pedidoreembolso_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoreembolso',
            name='chave_pix_paga',
            field=models.CharField(blank=True, max_length=80, verbose_name='chave PIX usada no pagamento'),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='tipo_chave_pix_paga',
            field=models.CharField(blank=True, max_length=10, verbose_name='tipo da chave usada'),
        ),
    ]
