# Generated by Django 4.2.27 on 2026-09-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_pcf', '0008_pedidoreembolso_chave_pix_paga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoreembolso',
            name='destino_corrigido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoreembolso',
            name='destino_corrigido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reembolsos_com_destino_corrigido', to=settings.AUTH_USER_MODEL),
        ),
    ]
