# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabado', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('area', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'Adm/Fin'), ('CR/RE', 'Cr/Re'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30)),
                ('apelido', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, help_text='Formato: DDD + número, apenas números', max_length=15, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('email_alternativo', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, help_text='Endereço de Lorena de preferência', max_length=200, null=True)),
                ('republica', models.CharField(blank=True, max_length=100, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_voluntarios')),
                ('restricao_alimentar', models.CharField(blank=True, max_length=100, null=True)),
                ('alimentacao', models.CharField(blank=True, choices=[('ONIVORO', 'Onívoro'), ('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano')], max_length=20, null=True)),
                ('comida_favorita', models.CharField(blank=True, max_length=100, null=True)),
                ('alergia', models.CharField(blank=True, max_length=100, null=True)),
                ('medicacao_continua', models.CharField(blank=True, max_length=100, null=True)),
                ('faculdade', models.CharField(blank=True, choices=[('EEL-USP', 'EEL-USP'), ('SERRA DOURADA', 'Serra Dourada'), ('UNISAL', 'Unisal'), ('UNIFATEA', 'Unifatea'), ('OUTRA', 'Outra'), ('NAO_ESTUDANTE', 'Não Estudante')], max_length=100, null=True)),
                ('n_usp', models.CharField(blank=True, max_length=20, null=True)),
                ('email_usp', models.EmailField(blank=True, max_length=254, null=True)),
                ('curso', models.CharField(blank=True, choices=[('ENGENHARIA_QUÍMICA', 'Engenharia Química'), ('ENGENHARIA_DE_PRODUÇÃO', 'Engenharia de Produção'), ('ENGENHARIA_FÍSICA', 'Engenharia Física'), ('ENGENHARIA_AMBIENTAL', 'Engenharia Ambiental'), ('ENGENHARIA_DE_MATERIAIS', 'Engenharia de Materiais'), ('ENGENHARIA_BIOQUÍMICA', 'Engenharia Bioquímica'), ('PSICOLOGIA', 'Psicologia'), ('OUTRO', 'Outro'), ('NAO_ESTUDANTE', 'Não Estudante')], max_length=100, null=True)),
                ('ano_faculdade', models.IntegerField(blank=True, null=True)),
                ('trabalha', models.BooleanField(default=False)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talento', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['talento'],
            },
        ),
        migrations.CreateModel(
            name='PresencaVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=15)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_voluntarios', to='sabado.sabado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas_voluntarios', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='voluntario',
            name='talentos',
            field=models.ManyToManyField(blank=True, to='voluntario.talento'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
