# Generated by Django 4.2.27 on 2026-01-05 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='ativo',
        ),
    ]
