# Generated by Django 4.2.27 on 2026-01-18 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencavoluntario',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas_voluntarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
