# Generated by Django 4.2.27 on 2026-01-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talento', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['talento'],
            },
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='data_entrada_projeto',
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='data_saida_projeto',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='alergia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='curso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='email_alternativo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='faculdade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='medicacao_continua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='republica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='restricao_alimentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='talentos',
            field=models.ManyToManyField(blank=True, to='voluntario.talento'),
        ),
    ]
