# Generated by Django 4.2.27 on 2026-01-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_presencavoluntario_registrado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='ano_faculdade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='comida_favorita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='email_usp',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='n_usp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='trabalha',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='celular',
            field=models.CharField(blank=True, help_text='Formato: DDD + número, apenas números', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='curso',
            field=models.CharField(blank=True, choices=[('ENGENHARIA_QUÍMICA', 'Engenharia Química'), ('ENGENHARIA_DE_PRODUÇÃO', 'Engenharia de Produção'), ('ENGENHARIA_FÍSICA', 'Engenharia Física'), ('ENGENHARIA_AMBIENTAL', 'Engenharia Ambiental'), ('ENGENHARIA_DE_MATERIAIS', 'Engenharia de Materiais'), ('ENGENHARIA_BIOQUÍMICA', 'Engenharia Bioquímica'), ('PSICOLOGIA', 'Psicologia'), ('OUTRO', 'Outro'), ('NAO_ESTUDANTE', 'Não Estudante')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço de Lorena de preferência', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='faculdade',
            field=models.CharField(blank=True, choices=[('EEL-USP', 'EEL-USP'), ('SERRA DOURADA', 'Serra Dourada'), ('UNISAL', 'Unisal'), ('UNIFATEA', 'Unifatea'), ('OUTRA', 'Outra'), ('NAO_ESTUDANTE', 'Não Estudante')], max_length=100, null=True),
        ),
    ]
