# Generated by Django 4.2.27 on 2026-01-06 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_remove_voluntario_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=15)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
