# Generated by Django 4.2.27 on 2026-01-16 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0002_talento_remove_voluntario_data_entrada_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
