# Generated by Django 4.2.27 on 2026-01-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0003_voluntario_ano_faculdade_voluntario_comida_favorita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='alergia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='medicacao_continua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='restricao_alimentar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
