# Generated by Django 4.2.27 on 2026-04-22 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0003_ocorrencia_regra_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_deletadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='automatico',
            field=models.BooleanField(default=False, help_text='True se gerada automaticamente por acúmulo'),
        ),
    ]
