# Generated by Django 4.2.27 on 2026-07-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0006_seed_regras'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='is_matricula',
            field=models.BooleanField(default=False, help_text='Se marcado, o voluntário pode acessar e usar a tela de Matrícula de Atendidos.'),
        ),
    ]
