# Generated by Django 4.2.27 on 2026-07-28 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0008_seed_is_matricula_triade'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo/posição na hierarquia (ex.: Presidente, Líder Educacional Geral, Líder de Sala).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='lider',
            field=models.ForeignKey(blank=True, help_text='Líder direto deste voluntário (monta o organograma; deixe vazio para o topo, ex.: Presidente).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricoLideranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(help_text='Cargo/posição liderada (ex.: Líder de Sala Violeta, LEG, Presidente).', max_length=100)),
                ('area', models.CharField(blank=True, choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'Adm/Fin'), ('CR/RE', 'Cr/Re'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], help_text='Área liderada (opcional).', max_length=30, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, help_text='Deixe vazio se ainda está no cargo.', null=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_lideranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Liderança',
                'verbose_name_plural': 'Históricos de Liderança',
                'ordering': ['area', '-data_inicio'],
            },
        ),
    ]
