# Generated by Django 4.2.27 on 2026-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0009_voluntario_cargo_voluntario_lider_historicolideranca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('LIDER', 'Líder'), ('LEG', 'Líder Educacional Geral'), ('VICE', 'Vice-Presidente'), ('PRESIDENTE', 'Presidente')], help_text='Cargo/posição na hierarquia.', max_length=100, null=True),
        ),
    ]
