# Generated by Django 4.2.27 on 2026-08-12 18:40

from django.db import migrations
import voluntario.models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0013_alter_historicolideranca_area_alter_voluntario_area'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voluntario',
            managers=[
                ('objects', voluntario.models.VoluntarioManager()),
            ],
        ),
    ]
