# Generated by Django 4.2.27 on 2026-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0016_regra_faltou_tres_sabados_seguidos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolideranca',
            options={'ordering': ['area', 'data_inicio'], 'verbose_name': 'Histórico de Liderança', 'verbose_name_plural': 'Históricos de Liderança'},
        ),
        migrations.AddField(
            model_name='historicolideranca',
            name='descricao',
            field=models.TextField(blank=True, help_text='Opcional: o que marcou essa gestão, o que foi deixado para a próxima. Aparece na linha de sucessão do histórico de líderes.', verbose_name='como foi a passagem'),
        ),
    ]
