# Generated by Django 4.2.27 on 2026-09-02 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0017_alter_historicolideranca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicolideranca',
            name='foto',
            field=models.ImageField(blank=True, help_text='Só é necessária para quem não tem ficha; com ficha, usamos a foto do perfil.', null=True, upload_to='lideres_historico', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='historicolideranca',
            name='nome_avulso',
            field=models.CharField(blank=True, help_text='Use quando a pessoa não tem ficha — é como ela vai aparecer na história.', max_length=120, verbose_name='nome ou apelido'),
        ),
        migrations.AlterField(
            model_name='historicolideranca',
            name='voluntario',
            field=models.ForeignKey(blank=True, help_text='Quem liderou, se tiver ficha no sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_lideranca', to=settings.AUTH_USER_MODEL),
        ),
    ]
