# Generated by Django 4.2.27 on 2026-09-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0018_historicolideranca_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolideranca',
            name='cargo',
            field=models.CharField(help_text='Cargo/posição liderada (ex.: Líder de Sala Violeta, LEG, Presidente). A tela liga a seta de sucessão entre quem teve o MESMO cargo, então escreva igual nos registros da mesma função.', max_length=100),
        ),
    ]
