# Generated by Django 4.2.27 on 2026-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntario', '0020_email_unico_por_voluntario'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Para a ADM pagar seu reembolso direto. Fica visível só para o Financeiro, na hora de pagar.', max_length=80, verbose_name='chave PIX'),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CELULAR', 'Celular'), ('EMAIL', 'E-mail'), ('ALEATORIA', 'Chave aleatória')], max_length=10, verbose_name='tipo da chave PIX'),
        ),
    ]
