# Generated by Django 4.2.27 on 2026-08-12 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('area', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], help_text='Para qual área do projeto é esta demanda.', max_length=30, verbose_name='área atendida')),
                ('o_que_pediram', models.TextField(blank=True, verbose_name='o que a área pediu')),
                ('o_que_fizemos', models.TextField(blank=True, verbose_name='o que já fizemos no site')),
                ('status', models.CharField(choices=[('IDEIA', 'Ideia'), ('CONVERSANDO', 'Conversando com a área'), ('ESPERANDO_AREA', 'Esperando a área'), ('FAZENDO', 'Fazendo'), ('ENTREGUE', 'Entregue'), ('PAUSADO', 'Pausado'), ('DESCARTADO', 'Descartado')], default='IDEIA', max_length=20)),
                ('retorno', models.CharField(choices=[('SEM_CONTATO', 'Ainda não procuramos'), ('AGUARDANDO', 'Procuramos, aguardando resposta'), ('RESPONDEU', 'Respondeu'), ('NAO_RESPONDE', 'Não respondeu')], default='SEM_CONTATO', max_length=20, verbose_name='retorno da área')),
                ('prioridade', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=10)),
                ('entregue_em', models.DateField(blank=True, null=True, verbose_name='entregue em')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato_na_area', models.ForeignKey(blank=True, help_text='Com quem falamos nessa área.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_como_contato', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_criadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demanda',
                'verbose_name_plural': 'demandas',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDemanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('CONVERSA', 'Conversa com a área'), ('COBRANCA', 'Cobrança'), ('RETORNO', 'Retorno da área'), ('ENTREGA', 'Entrega no site'), ('NOTA', 'Anotação')], default='NOTA', max_length=20)),
                ('descricao', models.TextField(verbose_name='o que aconteceu')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_demanda', to=settings.AUTH_USER_MODEL)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='projetos.demanda')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
