# Generated by Django 4.2.27 on 2026-09-12 19:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendido', '0009_listaespera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Bazar 2026', max_length=120)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('etapa', models.CharField(choices=[('NAO_COMECOU', 'Ainda não começou'), ('PRIMEIRA', '1ª etapa — cota de pontos'), ('SEGUNDA', '2ª etapa — livre, sem pontos'), ('ENCERRADO', 'Encerrado')], default='NAO_COMECOU', help_text='A coordenação vira a chave na hora certa. Não muda sozinho.', max_length=12)),
                ('cota_inicial', models.PositiveSmallIntegerField(default=5, help_text='Pontos que cada atendido recebe na 1ª etapa.', validators=[django.core.validators.MinValueValidator(1)])),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bazares_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bazar',
                'verbose_name_plural': 'Bazares',
                'ordering': ['-data', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('pontos', models.PositiveSmallIntegerField(help_text='Quantos pontos uma peça desta categoria custa.', validators=[django.core.validators.MinValueValidator(1)])),
                ('estoque_inicial', models.PositiveIntegerField(default=0, help_text='Quantas peças entraram no Bazar. 0 = não controlado.')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem dos botões na tela de atendimento.')),
                ('ativo', models.BooleanField(default=True)),
                ('bazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='bazar.bazar')),
            ],
            options={
                'verbose_name': 'Categoria de peça',
                'verbose_name_plural': 'Categorias de peça',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('PRIMEIRA', '1ª etapa'), ('SEGUNDA', '2ª etapa')], max_length=10)),
                ('sala_do_bazar', models.CharField(blank=True, help_text='Sala física da conferência. Ex.: Sala 1.', max_length=30)),
                ('retirado_por', models.CharField(choices=[('ATENDIDO', 'O próprio atendido'), ('PAI_MAE', 'Pai ou mãe'), ('RESPONSAVEL', 'Responsável cadastrado'), ('OUTRO', 'Outra pessoa autorizada')], default='ATENDIDO', help_text='Quem levou a sacola. O atendido nem sempre está presente.', max_length=12)),
                ('retirado_por_nome', models.CharField(blank=True, help_text='Nome de quem levou, quando não é o próprio atendido.', max_length=120)),
                ('cota_no_momento', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_no_bazar', to='atendido.atendido')),
                ('bazar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to='bazar.bazar')),
                ('conferido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_conferidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retirada',
                'verbose_name_plural': 'Retiradas',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ItemRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pontos_unitarios', models.PositiveSmallIntegerField()),
                ('pontos_total', models.PositiveIntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='bazar.categoria')),
                ('retirada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bazar.retirada')),
            ],
            options={
                'verbose_name': 'Item da retirada',
                'verbose_name_plural': 'Itens da retirada',
            },
        ),
        migrations.AddConstraint(
            model_name='retirada',
            constraint=models.UniqueConstraint(condition=models.Q(('finalizada_em__isnull', False)), fields=('bazar', 'atendido', 'etapa'), name='uma_retirada_finalizada_por_etapa'),
        ),
        migrations.AddConstraint(
            model_name='itemretirada',
            constraint=models.UniqueConstraint(fields=('retirada', 'categoria'), name='uma_linha_por_categoria_na_retirada'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('bazar', 'nome'), name='categoria_unica_por_bazar'),
        ),
    ]
