# Generated by Django 4.2.27 on 2026-09-14 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirada',
            name='sala_do_bazar',
            field=models.CharField(blank=True, help_text='Sala digitada à mão, antes de as salas virarem lista.', max_length=30),
        ),
        migrations.CreateModel(
            name='SalaDoBazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex.: Sala 1, Recepção.', max_length=30)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem dos botões na tela.')),
                ('ativo', models.BooleanField(default=True)),
                ('bazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='bazar.bazar')),
            ],
            options={
                'verbose_name': 'Sala do Bazar',
                'verbose_name_plural': 'Salas do Bazar',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='retirada',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retiradas', to='bazar.saladobazar'),
        ),
        migrations.AddConstraint(
            model_name='saladobazar',
            constraint=models.UniqueConstraint(fields=('bazar', 'nome'), name='uma_sala_por_nome_no_bazar'),
        ),
    ]
