# Generated by Django 4.2.27 on 2026-09-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0009_listaespera'),
        ('bazar', '0002_salas_do_bazar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retirada',
            name='uma_retirada_finalizada_por_etapa',
        ),
        migrations.AddField(
            model_name='retirada',
            name='sem_retirada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retirada',
            name='visitante_motivo',
            field=models.CharField(blank=True, help_text='Por que foi atendida fora do cadastro.', max_length=200),
        ),
        migrations.AddField(
            model_name='retirada',
            name='visitante_nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='retirada',
            name='atendido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retiradas_no_bazar', to='atendido.atendido'),
        ),
        migrations.AddConstraint(
            model_name='retirada',
            constraint=models.UniqueConstraint(condition=models.Q(('atendido__isnull', False), ('etapa', 'PRIMEIRA'), ('finalizada_em__isnull', False)), fields=('bazar', 'atendido', 'etapa'), name='uma_retirada_finalizada_na_primeira_etapa'),
        ),
    ]
