# Generated by Django 4.2.27 on 2026-09-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazar', '0003_visitante_e_sem_retirada'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirada',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retirada',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiradas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retirada',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='retirada',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
