# Generated by Django 4.2.27 on 2026-01-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabado', '0005_disponibilidadevoluntario_saude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('PAPELARIA', 'Papelaria'), ('LIMPEZA', 'Limpeza'), ('ALIMENTACAO', 'Alimentação'), ('ESCRITORIO', 'Escritório'), ('ESPORTES', 'Esportes'), ('ARTESANATO', 'Artesanato'), ('HIGIENE', 'Higiene'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PAC', 'Pacote'), ('CX', 'Caixa'), ('TUBO', 'Tubo'), ('METRO', 'Metro'), ('L', 'Litro'), ('KG', 'Quilo'), ('FOLHA', 'Folha'), ('ROLO', 'Rolo'), ('OUTROS', 'Outros')], default='UN', max_length=20)),
                ('quantidade_minima', models.DecimalField(decimal_places=2, default=0, help_text='Quantidade mínima para alerta de estoque baixo', max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste de Inventário')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='supply.item')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_supply', to=settings.AUTH_USER_MODEL)),
                ('sabado', models.ForeignKey(blank=True, help_text='Sábado relacionado à movimentação (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_supply', to='sabado.sabado')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-criado_em'],
            },
        ),
    ]
