# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sabado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_supply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='sabado',
            field=models.ForeignKey(blank=True, help_text='Sábado relacionado à movimentação (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_supply', to='sabado.sabado'),
        ),
    ]
