# Generated by Django 4.2.27 on 2026-04-06 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('PAC', 'Pacote'), ('CX', 'Caixa'), ('TUBO', 'Tubo'), ('METRO', 'Metro'), ('L', 'Litro'), ('KG', 'Quilo'), ('FOLHA', 'Folha'), ('ROLO', 'Rolo'), ('OUTROS', 'Outros')], default='UN', max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('local_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_local', models.CharField(blank=True, choices=[('MERCADO', 'Mercado'), ('PAPELARIA', 'Papelaria'), ('SALINHA', 'Salinha'), ('ARTIGO DE FESTA', 'Artigo de Festa'), ('OUTROS', 'Outros')], max_length=100, null=True)),
                ('area', models.CharField(blank=True, choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/FIN'), ('CR/RE', 'CR/RE'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projatos'), ('TRIADE', 'Tríade')], max_length=30, null=True)),
                ('requisitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_requisitados', to=settings.AUTH_USER_MODEL)),
                ('sabado', models.ForeignKey(blank=True, help_text='Sábado relacionado ao pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_do_sabado', to='sabado.sabado')),
            ],
        ),
    ]
