# Generated by Django 4.2.27 on 2026-07-18 22:59

from django.db import migrations, models
import django.db.models.deletion


def migrar_locais_pedidos(apps, schema_editor):
    Local = apps.get_model('supply', 'Local')
    Pedido = apps.get_model('supply', 'Pedido')
    tipos = {
        'MERCADO': 'MERCADO',
        'PAPELARIA': 'PAPELARIA',
        'ARTIGO DE FESTA': 'ARTIGOS_FESTA',
        'OUTROS': 'OUTROS',
        'SALINHA': 'OUTROS',
    }
    rotulos = {
        'MERCADO': 'Mercado', 'PAPELARIA': 'Papelaria',
        'ARTIGO DE FESTA': 'Artigos de festa', 'OUTROS': 'Outros',
        'SALINHA': 'Salinha',
    }
    for pedido in Pedido.objects.exclude(local_compra__isnull=True).exclude(local_compra='') | Pedido.objects.exclude(tipo_local__isnull=True).exclude(tipo_local=''):
        nome = (pedido.local_compra or rotulos.get(pedido.tipo_local) or 'Local não informado').strip()
        tipo = tipos.get(pedido.tipo_local, 'OUTROS')
        local, _ = Local.objects.get_or_create(nome=nome, tipo=tipo)
        pedido.local_id = local.id
        pedido.save(update_fields=['local'])


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('MERCADO', 'Mercado'), ('SUPERMERCADO', 'Supermercado'), ('PAPELARIA', 'Papelaria'), ('ARTIGOS_FESTA', 'Artigos de festa'), ('ATACADISTA', 'Atacadista'), ('LOJA_UTILIDADES', 'Loja de utilidades'), ('ONLINE', 'Loja online'), ('OUTROS', 'Outros')], default='OUTROS', max_length=30)),
                ('localizacao', models.CharField(blank=True, max_length=255, verbose_name='endereço/localização')),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('numero_contato', models.CharField(blank=True, max_length=30, verbose_name='número de contato')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='contato possui WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local de compra',
                'verbose_name_plural': 'Locais de compra',
                'ordering': ('nome',),
            },
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(fields=('nome', 'tipo'), name='local_nome_tipo_unicos'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='supply.local'),
        ),
        migrations.RunPython(migrar_locais_pedidos, migrations.RunPython.noop),
        migrations.RemoveField(model_name='pedido', name='local_compra'),
        migrations.RemoveField(model_name='pedido', name='tipo_local'),
    ]
