# Generated by Django 4.2.27 on 2026-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_local_remove_pedido_local_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='link',
            field=models.URLField(blank=True, verbose_name='link da imagem'),
        ),
    ]
