# Generated by Django 4.2.27 on 2026-07-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_pedido_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='especificar',
            field=models.TextField(blank=True),
        ),
    ]
