# Generated by Django 4.2.27 on 2026-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0008_remove_pedido_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('PAPELARIA', 'Papelaria'), ('LIMPEZA', 'Limpeza'), ('ALIMENTACAO', 'Alimentação'), ('ESPORTES', 'Esportes'), ('ARTESANATO', 'Artesanato'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50),
        ),
    ]
