# Generated by Django 4.2.27 on 2026-09-13 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supply', '0009_alter_item_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoSabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiais_conferidos_em', models.DateTimeField(blank=True, null=True)),
                ('pedidos_conferidos_em', models.DateTimeField(blank=True, null=True)),
                ('materiais_conferidos_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_de_material', to=settings.AUTH_USER_MODEL)),
                ('pedidos_conferidos_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_de_pedido', to=settings.AUTH_USER_MODEL)),
                ('sabado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fechamento_supply', to='sabado.sabado')),
            ],
            options={
                'verbose_name': 'fechamento do sábado',
                'verbose_name_plural': 'fechamentos do sábado',
            },
        ),
    ]
