# Generated by Django 4.2.27 on 2026-09-02 11:20

import acervo.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Deixe vazio para gerar a partir do nome.', max_length=80, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='O que entra nesta coleção, e o que não entra.', verbose_name='descrição')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Menor aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder a coleção sem apagar nada.')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'coleção',
                'verbose_name_plural': 'coleções',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='título')),
                ('arquivo', models.FileField(upload_to=acervo.models.caminho_do_documento)),
                ('ano', models.PositiveSmallIntegerField(help_text='Ano a que o documento se refere — o da postulação, não o do upload.')),
                ('nome_avulso', models.CharField(blank=True, help_text='Use quando a pessoa não tem ficha no sistema.', max_length=120, verbose_name='nome')),
                ('cargo_pretendido', models.CharField(blank=True, help_text='Ex.: Presidente, LEG, Líder de Sala Azul.', max_length=100)),
                ('resultado', models.CharField(blank=True, choices=[('ELEITO', 'Eleito'), ('NAO_ELEITO', 'Não eleito')], help_text='Em branco quando não se aplica à coleção.', max_length=12)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='acervo.colecao', verbose_name='coleção')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(blank=True, help_text='Quem o documento se refere, se estiver cadastrado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_no_acervo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-ano', 'titulo'],
            },
        ),
    ]
