# Generated by Django 4.2.27 on 2026-09-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0002_colecao_de_postulacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='origem_drive_id',
            field=models.CharField(blank=True, editable=False, help_text='Preenchido pela sincronização. Vazio em documento cadastrado na tela.', max_length=100, null=True, unique=True, verbose_name='ID no Google Drive'),
        ),
        migrations.CreateModel(
            name='SincronizacaoDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comecou_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminou_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RODANDO', 'Em andamento'), ('OK', 'Concluída'), ('ERRO', 'Falhou')], default='RODANDO', max_length=10)),
                ('trazidos', models.PositiveIntegerField(default=0)),
                ('pulados', models.PositiveIntegerField(default=0)),
                ('detalhe', models.TextField(blank=True, help_text='Resumo por coleção e motivos.')),
                ('disparada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes_do_acervo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sincronização com o Drive',
                'verbose_name_plural': 'sincronizações com o Drive',
                'ordering': ['-comecou_em'],
            },
        ),
    ]
