# Generated by Django 4.2.27 on 2026-09-13 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sabado', '0003_sabado_hora_fim_sabado_hora_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada')], default='RASCUNHO', max_length=10)),
                ('revisao', models.PositiveIntegerField(default=1, editable=False)),
                ('publicada_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sabado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escala_ajudas', to='sabado.sabado')),
            ],
            options={
                'verbose_name': 'Escala de ajudas',
                'verbose_name_plural': 'Escalas de ajudas',
                'ordering': ['-sabado__data'],
            },
        ),
        migrations.CreateModel(
            name='NecessidadeAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='pessoas necessárias')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='ajudas.escalaajuda')),
            ],
            options={
                'ordering': ['hora_inicio', 'area'],
            },
        ),
        migrations.CreateModel(
            name='Ajuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_destino', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajudas', to='ajudas.escalaajuda')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajudas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hora_inicio', 'area_destino', 'voluntario__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='necessidadeajuda',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='necessidade_horarios_em_ordem'),
        ),
        migrations.AddConstraint(
            model_name='escalaajuda',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('publicada_em__isnull', True), ('status', 'RASCUNHO')), models.Q(('publicada_em__isnull', False), ('status', 'PUBLICADA')), _connector='OR'), name='ajudas_status_publicacao_consistente'),
        ),
        migrations.AddIndex(
            model_name='ajuda',
            index=models.Index(fields=['escala', 'voluntario', 'hora_inicio'], name='ajudas_ajud_escala__dcc0d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='ajuda',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='ajuda_horarios_em_ordem'),
        ),
    ]
