# Generated by Django 4.2.27 on 2026-06-22 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sabado', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRondaSabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE_SORTEIO', 'Pendente de Sorteio'), ('SORTEADA', 'Sorteada — Aguardando Aprovação'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], default='PENDENTE_SORTEIO', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('sorteado_em', models.DateTimeField(blank=True, null=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rondas_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_ronda_criadas', to=settings.AUTH_USER_MODEL)),
                ('sabado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_ronda', to='sabado.sabado')),
            ],
            options={
                'verbose_name': 'Configuração de Ronda',
                'verbose_name_plural': 'Configurações de Ronda',
                'ordering': ['-sabado__data'],
            },
        ),
        migrations.CreateModel(
            name='LocalRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Local de Ronda',
                'verbose_name_plural': 'Locais de Ronda',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='ronda.configuracaorondasabado')),
            ],
            options={
                'verbose_name': 'Horário de Ronda',
                'verbose_name_plural': 'Horários de Ronda',
                'ordering': ['ordem', 'hora_inicio'],
                'unique_together': {('configuracao', 'hora_inicio', 'hora_fim')},
            },
        ),
        migrations.CreateModel(
            name='ScoreRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField()),
                ('pontos', models.PositiveSmallIntegerField(default=0)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_ronda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score de Ronda',
                'verbose_name_plural': 'Scores de Ronda',
                'ordering': ['-pontos'],
                'unique_together': {('voluntario', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='EscalaRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_substituto', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='ronda.horarioronda')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='ronda.localronda')),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas_ronda', to=settings.AUTH_USER_MODEL)),
                ('voluntario_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_substituidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escala de Ronda',
                'verbose_name_plural': 'Escalas de Ronda',
                'unique_together': {('horario', 'local', 'voluntario')},
            },
        ),
    ]
