# Generated by Django 4.2.27 on 2026-07-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ronda', '0002_seed_locais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioronda',
            options={'ordering': ['ordem', 'hora_inicio', 'local__nome'], 'verbose_name': 'Horário de Ronda', 'verbose_name_plural': 'Horários de Ronda'},
        ),
        migrations.AlterUniqueTogether(
            name='horarioronda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='horarioronda',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horarios', to='ronda.localronda'),
        ),
        migrations.AlterUniqueTogether(
            name='horarioronda',
            unique_together={('configuracao', 'hora_inicio', 'hora_fim', 'local')},
        ),
    ]
