# Generated by Django 4.2.27 on 2026-07-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronda', '0003_alter_horarioronda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaorondasabado',
            name='dia_de_evento',
            field=models.BooleanField(default=False, help_text='Ronda rotativa: 4 pessoas fixas por local (2 duplas), sem horários.'),
        ),
        migrations.AddField(
            model_name='escalaronda',
            name='dupla',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dupla fixa (1 ou 2) no modo dia de evento.', null=True),
        ),
        migrations.AlterField(
            model_name='horarioronda',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioronda',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
