"""
Django settings for TESTE project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Vem do .env. O padrão é False: se a variável não existir no servidor, o site
# roda SEGURO (sem expor stack trace, SQL e configurações em telas de erro).
# Para desenvolver localmente, coloque DEBUG=True no seu .env.
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = ['pcf.pythonanywhere.com', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'atendido',
    'voluntario',
    'semanario',
    'sabado',
    'supply',
    'adm',
    'forms_pcf',
    'ronda',
    'gerenciamento',
    'parceiros',
    'revista',
    'editais',
    'projetos',
    'acervo',
    'estudio',
    'notificacoes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TESTE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'atendido.novos_context.atendidos_filtrados',
                'TESTE.versao_estatica.versao_estatica',
            ],
        },
    },
]

WSGI_APPLICATION = 'TESTE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config("DATA_BASE_ENGINE"),
        'NAME': config("DATA_BASE_NAME"),
        'USER': config("DATA_BASE_USER"),
        'PASSWORD': config("DATA_BASE_PASSWORD"),
        'HOST': config("DATA_BASE_HOST"),
        'PORT':config("DATA_BASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "voluntario.Voluntario"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Mantém URLs como /static/css/pcf.css, compatíveis com o mapeamento
        # atual do PythonAnywhere, e ainda gera versões comprimidas.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / "media"

LOGIN_REDIRECT_URL = 'inicio'
LOGIN_URL = 'login'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 180  # 180 dias em segundos
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
# Cookie "Secure" só viaja em HTTPS. Em produção é obrigatório; em
# desenvolvimento (http://localhost) ele impediria o login de funcionar.
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ─── Segurança (aplicada apenas fora do modo debug) ───
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
if not DEBUG:
    # O PythonAnywhere encerra o HTTPS no proxy; sem isto o Django acha que a
    # requisição é http e os cookies "Secure" não são enviados.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_CONTENT_TYPE_NOSNIFF = True      # impede o browser de "adivinhar" o tipo do arquivo
    SECURE_REFERRER_POLICY = 'same-origin'  # não vaza a URL interna ao sair do site
    X_FRAME_OPTIONS = 'DENY'                # bloqueia o site dentro de iframe (clickjacking)
    # Obs.: o redirecionamento para HTTPS é feito pelo próprio PythonAnywhere
    # ("Force HTTPS" na aba Web) — por isso não usamos SECURE_SSL_REDIRECT aqui,
    # que poderia causar laço de redirecionamento atrás do proxy.

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = config("EMAIL_PORT")
EMAIL_USE_TLS = config("EMAIL_USE_TLS")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

# ─── Notificações push (Web Push / VAPID) ───
# Gerar UMA VEZ SÓ com: python manage.py gerar_chaves_vapid
# Trocar a chave pública invalida TODAS as inscrições existentes e obriga cada
# voluntário a reativar as notificações no aparelho dele.
# O default="" é de propósito: sem ele, o projeto quebra em qualquer máquina que
# não tenha as chaves — incluindo a suíte de testes.
VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY", default="")
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY", default="")
VAPID_ADMIN_EMAIL = config("VAPID_ADMIN_EMAIL", default="")

# ─── Acervo ← Google Drive ───
# Conta de SERVIÇO, não OAuth de usuário: em app não verificado pelo Google, o
# refresh token do OAuth expira em 7 dias e a sincronização pararia sozinha
# toda semana. A conta de serviço não expira — basta compartilhar a pasta do
# Drive com o e-mail dela como Leitor.
#
# ACERVO_DRIVE_CREDENCIAIS: caminho do JSON da chave, FORA do repositório.
# ACERVO_DRIVE_PASTA_ID: o trecho depois de /folders/ na URL da pasta.
# Vazios de propósito: sem eles o botão aparece desligado e explica o que falta,
# em vez de o projeto quebrar em toda máquina que não tenha a credencial.
ACERVO_DRIVE_CREDENCIAIS = config("ACERVO_DRIVE_CREDENCIAIS", default="")
ACERVO_DRIVE_PASTA_ID = config("ACERVO_DRIVE_PASTA_ID", default="")

# Alternativa à conta de serviço: o PCF lê o Drive COMO uma pessoa, com a
# permissão que ela já tem. É a saída quando a pasta é da organização e quem
# configura consegue LER mas não consegue COMPARTILHAR com outra identidade —
# que é justamente o caso deste projeto.
#
# Obtidos uma vez com: python manage.py autorizar_acervo_drive
# O refresh token é SEGREDO, como uma senha.
ACERVO_DRIVE_OAUTH_CLIENT_ID = config("ACERVO_DRIVE_OAUTH_CLIENT_ID", default="")
ACERVO_DRIVE_OAUTH_CLIENT_SECRET = config("ACERVO_DRIVE_OAUTH_CLIENT_SECRET", default="")
ACERVO_DRIVE_OAUTH_REFRESH_TOKEN = config("ACERVO_DRIVE_OAUTH_REFRESH_TOKEN", default="")

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'voluntario.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'notificacoes': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'acervo': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
