# Generated by Django 4.2.27 on 2026-08-12 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=200, unique=True, verbose_name='o que perguntar')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_busca', models.DateTimeField(blank=True, null=True)),
                ('resultados_ultima_busca', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'consulta de busca',
                'verbose_name_plural': 'consultas de busca',
                'ordering': ['termo'],
            },
        ),
        migrations.CreateModel(
            name='FonteEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('tipo', models.CharField(choices=[('RSS', 'RSS / Atom'), ('HTML', 'Página HTML')], default='RSS', max_length=6)),
                ('seletor_item', models.CharField(blank=True, help_text='CSS de cada edital na página. Só para fonte HTML.', max_length=200, verbose_name='seletor do item')),
                ('seletor_titulo', models.CharField(blank=True, max_length=200, verbose_name='seletor do título')),
                ('seletor_link', models.CharField(blank=True, max_length=200, verbose_name='seletor do link')),
                ('seletor_descricao', models.CharField(blank=True, max_length=200, verbose_name='seletor da descrição')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_coleta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('itens_ultima_coleta', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'fonte de editais',
                'verbose_name_plural': 'fontes de editais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=80, unique=True)),
                ('peso', models.IntegerField(default=1, help_text='Positivo atrai, negativo descarta.')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'palavra-chave',
                'verbose_name_plural': 'palavras-chave',
                'ordering': ['-peso', 'termo'],
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='título')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('requisitos', models.TextField(blank=True, verbose_name='o que precisamos')),
                ('link', models.URLField(max_length=500)),
                ('origem', models.CharField(choices=[('ROBO', 'Fonte fixa'), ('BUSCA', 'Varredura na web'), ('MANUAL', 'Cadastro manual')], default='ROBO', max_length=6)),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='prazo de inscrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor previsto')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('AVALIANDO', 'Avaliando'), ('VAMOS_CONCORRER', 'Vamos concorrer'), ('INSCRITO', 'Inscrito'), ('DESCARTADO', 'Descartado'), ('ENCERRADO', 'Encerrado')], default='NOVO', max_length=20)),
                ('relevancia', models.IntegerField(default=0)),
                ('termos_encontrados', models.CharField(blank=True, max_length=250)),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('chave', models.CharField(db_index=True, max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, help_text='Qual pergunta trouxe este edital, quando veio da varredura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editais', to='editais.consultabusca')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editais', to='editais.fonteedital')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'edital',
                'verbose_name_plural': 'editais',
                'ordering': ['-relevancia', 'prazo', '-criado_em'],
            },
        ),
    ]
