# Generated by Django 4.2.27 on 2026-09-02 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revista', '0002_revista_atividades_descartadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('FOTO', 'Foto'), ('DECORACAO', 'Decoração'), ('LOGO', 'Logo')], default='FOTO', max_length=10)),
                ('arquivo', models.ImageField(upload_to='estudio/assets')),
                ('apelido', models.SlugField(blank=True, help_text='Para os presets acharem esta arte. Ex.: maozinhas-topo.', max_length=60, null=True, unique=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('tipo', models.CharField(choices=[('REVISTA', 'Revistinha'), ('ATA', 'Ata'), ('CARTAZ', 'Cartaz'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('largura', models.PositiveIntegerField(default=794)),
                ('altura', models.PositiveIntegerField(default=1123)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_estudio', to=settings.AUTH_USER_MODEL)),
                ('revista', models.OneToOneField(blank=True, help_text='Preenchido quando o documento é o layout de uma revista.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento', to='revista.revista')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('cor_de_fundo', models.CharField(default='#ffffff', max_length=20)),
                ('preset', models.CharField(blank=True, max_length=30)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='estudio.documento')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('FORMA', 'Forma')], max_length=8)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('largura', models.PositiveIntegerField(default=200)),
                ('altura', models.PositiveIntegerField(default=80)),
                ('rotacao', models.SmallIntegerField(default=0, verbose_name='rotação')),
                ('z', models.SmallIntegerField(default=0, verbose_name='camada')),
                ('texto', models.TextField(blank=True)),
                ('estilo', models.JSONField(blank=True, default=dict)),
                ('travado', models.BooleanField(default=False, help_text='Elemento travado não se arrasta por acidente.', verbose_name='travado')),
                ('imagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='estudio.asset')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='estudio.pagina')),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': 'elementos',
                'ordering': ['z', 'pk'],
            },
        ),
    ]
