# Generated by Django 4.2.27 on 2026-08-09 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0003_alter_lancamento_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo, exatamente como deve sair no recibo/nota.', max_length=150)),
                ('status', models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone / WhatsApp')),
                ('documento', models.CharField(blank=True, help_text='Opcional. Necessário apenas se for emitir recibo.', max_length=20, verbose_name='CPF / CNPJ')),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Quanto costuma doar por mês. Só orientativo — não gera cobrança.', max_digits=10, null=True, verbose_name='valor de referência')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Voluntário do CR que cuida dessa relação (a carteira).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parceiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(choices=[('CONTATO', 'Contato'), ('AGRADECIMENTO', 'Agradecimento'), ('COBRANCA', 'Lembrete de doação'), ('REUNIAO', 'Reunião'), ('OBSERVACAO', 'Observação')], default='CONTATO', max_length=15)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_parceiros', to=settings.AUTH_USER_MODEL)),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='parceiros.parceiro')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Mês a que a doação se refere. O dia é normalizado para 1.', verbose_name='mês de referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField(help_text='Data em que o dinheiro entrou. É ela que vale no fluxo de caixa e no DRE.')),
                ('forma', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência'), ('DINHEIRO', 'Dinheiro'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], default='PIX', max_length=15)),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lancamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicao', to='adm.lancamento')),
                ('parceiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='parceiros.parceiro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
                'ordering': ['-competencia', 'parceiro__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='contribuicao',
            constraint=models.UniqueConstraint(fields=('parceiro', 'competencia'), name='parceiro_uma_contribuicao_por_mes'),
        ),
    ]
