# Generated by Django 4.2.27 on 2026-08-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_conta_evento_lancamento_area_tetoarea_recargacartao_and_more'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuicao',
            name='conta',
            field=models.ForeignKey(blank=True, help_text='Onde o dinheiro caiu (ex.: BB, Caju).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to='adm.conta'),
        ),
    ]
