# Generated by Django 4.2.27 on 2026-01-17 03:34

from django.db import migrations, models
import django.db.models.deletion
import sabado.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaHorarioAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=sabado.models.proximo_sabado, unique=True)),
                ('tema', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadeVoluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_ao_projeto', models.BooleanField()),
                ('vai_de_carro', models.BooleanField(null=True)),
                ('alimentacao', models.CharField(blank=True, choices=[('ONIVORO', 'Onívoro'), ('VEGETARIANO', 'Vegetariano'), ('VEGANO', 'Vegano')], max_length=20, null=True)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('pode_ajudar', models.ManyToManyField(blank=True, to='sabado.faixahorarioajuda')),
                ('sabado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='sabado.sabado')),
            ],
        ),
    ]
