# Generated by Django 4.2.27 on 2026-01-17 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sabado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadevoluntario',
            name='voluntario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadevoluntario',
            unique_together={('sabado', 'voluntario')},
        ),
    ]
