# Generated by Django 4.2.27 on 2026-09-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabado',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(12, 30), verbose_name='horário de término'),
        ),
        migrations.AddField(
            model_name='sabado',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(6, 0), verbose_name='horário de início'),
        ),
        migrations.AddConstraint(
            model_name='sabado',
            constraint=models.CheckConstraint(check=models.Q(('hora_inicio__lt', models.F('hora_fim'))), name='sabado_horarios_em_ordem'),
        ),
    ]
