# Generated by Django 4.2.27 on 2026-01-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadevoluntario',
            name='alimentacao',
        ),
    ]
