# Generated by Django 4.2.27 on 2026-01-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0003_remove_disponibilidadevoluntario_alimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadevoluntario',
            name='vai_ao_projeto',
            field=models.BooleanField(default=True),
        ),
    ]
