# Generated by Django 4.2.27 on 2026-01-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabado', '0004_alter_disponibilidadevoluntario_vai_ao_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadevoluntario',
            name='saude',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
