# Generated by Django 4.2.27 on 2026-06-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SUPPLY', 'Supply'), ('REEMBOLSO', 'Reembolso')], default='MANUAL', max_length=10),
        ),
    ]
