# Generated by Django 4.2.27 on 2026-08-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_lancamento_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='origem',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SUPPLY', 'Supply'), ('REEMBOLSO', 'Reembolso'), ('DOACAO', 'Doação')], default='MANUAL', max_length=10),
        ),
    ]
