# Generated by Django 4.2.27 on 2026-08-20 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0003_alter_lancamento_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro físico')], default='BANCO', max_length=10)),
                ('controla_saldo', models.BooleanField(default=False, help_text='Ligue para cartão pré-pago: o saldo é recarga menos gasto. Deixe desligado para conta de banco, onde o extrato manda.', verbose_name='controlar saldo desta conta')),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('responsavel', models.ForeignKey(blank=True, help_text='Com quem está o cartão hoje.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_sob_responsabilidade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta',
                'verbose_name_plural': 'contas',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('teto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='teto de gasto')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='area',
            field=models.CharField(blank=True, choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], help_text='Para qual área do projeto foi este gasto.', max_length=30, verbose_name='área'),
        ),
        migrations.CreateModel(
            name='TetoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30)),
                ('competencia', models.DateField(verbose_name='mês de referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('definido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tetos_definidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teto de área',
                'verbose_name_plural': 'tetos de área',
                'ordering': ['-competencia', 'area'],
            },
        ),
        migrations.CreateModel(
            name='RecargaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area', models.CharField(blank=True, choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30, verbose_name='para qual área foi')),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('carregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recargas_feitas', to=settings.AUTH_USER_MODEL)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='adm.conta')),
            ],
            options={
                'verbose_name': 'recarga de cartão',
                'verbose_name_plural': 'recargas de cartão',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='conta',
            field=models.ForeignKey(blank=True, help_text='Banco, cartão ou dinheiro físico.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='adm.conta'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='adm.evento'),
        ),
        migrations.AddConstraint(
            model_name='tetoarea',
            constraint=models.UniqueConstraint(fields=('area', 'competencia'), name='um_teto_por_area_por_mes'),
        ),
    ]
