# Generated by Django 4.2.27 on 2026-09-22 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0006_lancamento_do_supply_deixa_de_ser_espelho'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateioDeGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate, help_text='O sábado. É ela que decide em qual semestre o teto desconta.', verbose_name='data do gasto')),
                ('total_a_ratear', models.DecimalField(decimal_places=2, help_text='Quanto saiu dos cartões neste dia, somando todos.', max_digits=10, verbose_name='total a ratear')),
                ('descricao', models.CharField(blank=True, help_text='Distingue dois rateios do mesmo dia. Ex.: materiais, lanches.', max_length=120, verbose_name='descrição')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_criados', to=settings.AUTH_USER_MODEL)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rateios_fechados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rateio de gasto',
                'verbose_name_plural': 'rateios de gasto',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LinhaDeRateio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz'), ('MARKETING', 'Marketing'), ('ADM/FIN', 'ADM/Fin'), ('CR/RE', 'Captação de Recursos & Relações Externas'), ('EVENTOS', 'Eventos'), ('GESTAO_DE_TALENTOS', 'Gestão de Talentos'), ('RECREACAO', 'Recreação'), ('SUPPLY', 'Supply'), ('PROJETOS', 'Projetos'), ('TRIADE', 'Tríade')], max_length=30, verbose_name='área')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rateio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='adm.rateiodegasto')),
            ],
            options={
                'verbose_name': 'linha de rateio',
                'verbose_name_plural': 'linhas de rateio',
                'ordering': ['area'],
            },
        ),
        migrations.AddConstraint(
            model_name='linhaderateio',
            constraint=models.UniqueConstraint(fields=('rateio', 'area'), name='uma_linha_por_area_no_rateio', violation_error_message='Esta área já tem linha neste rateio. Some no valor da linha existente em vez de criar outra.'),
        ),
    ]
