# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do atendido', max_length=50)),
                ('data_nascimento', models.DateField(help_text='Data de nascimento do atendido')),
                ('sala', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz')], help_text='Sala em que o atendido está sendo matriculado', max_length=20)),
                ('rg', models.CharField(blank=True, help_text='RG do atendido, somente números', max_length=9, null=True)),
                ('cpf', models.CharField(blank=True, help_text='CPF do atendido, somente números', max_length=11, null=True, unique=True)),
                ('contato', models.CharField(blank=True, help_text='Número de contato do atendido, somente números', max_length=11, null=True)),
                ('documento', models.FileField(blank=True, help_text='Documento do atendido (RG ou Certidão de Nascimento)', null=True, upload_to='documentos_atendidos')),
                ('escolaridade', models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], help_text='Escolaridade do atendido', max_length=100, null=True)),
                ('ano_escolar', models.CharField(blank=True, choices=[('1º ANO', '1º Ano'), ('2º ANO', '2º Ano'), ('3º ANO', '3º Ano'), ('4º ANO', '4º Ano'), ('5º ANO', '5º Ano'), ('6º ANO', '6º Ano'), ('7º ANO', '7º Ano'), ('8º ANO', '8º Ano'), ('9º ANO', '9º Ano'), ('1ª SÉRIE DO ENSINO MÉDIO', '1ª Série do Ensino Médio'), ('2ª SÉRIE DO ENSINO MÉDIO', '2ª Série do Ensino Médio'), ('3ª SÉRIE DO ENSINO MÉDIO', '3ª Série do Ensino Médio')], help_text='Ano escolar do atendido', max_length=50, null=True)),
                ('escola', models.CharField(blank=True, choices=[('ESCOLA RUI BRASIL', 'Escola Rui Brasil'), ('ESCOLA ESTADUAL ARNOLFO AZEVEDO', 'Escola Estadual Arnolfo Azevedo'), ('E.M PROFª HERMÍNIA FIGUEIRA DE AZEVEDO ALMEIDA', 'E.M Profª Hermínia Figueira de Azevedo Almeida'), ('CEMEI JÂNIO QUADROS', 'CEMEI Jânio Quadros'), ('APARECIDA GUEDES', 'Aparecida Guedes'), ('ESCOLA GABRIEL PRESTES', 'Escola Gabriel Prestes'), ('E.M PROFESSORA LEDA MARIA BILARD DE CARVALHO', 'E.M Professora Leda Maria Bilard de Carvalho'), ('E.E PROF. LUIZ DE CASTRO PINTO', 'E.E Prof. Luiz de Castro Pinto'), ('E.E PROF. FRANCISCO MARQUES DE OLIVEIRA JUNIOR', 'E.E Prof. Francisco Marques de Oliveira Junior'), ('EE PEI PROF.ª MIQUELINA CARTOLANO', 'EE PEI Prof.ª Miquelina Cartolano'), ('ETEC PADRE CARLOS LEÔNCIO DA SILVA', 'Etec Padre Carlos Leôncio da Silva'), ('ESCOLA MARIA AUXILIADORA', 'Escola Maria Auxiliadora'), ('ESCOLA ESTADUAL LEONOR GUIMARÃES', 'Escola Estadual Leonor Guimarães'), ('OUTRO', 'Outro')], help_text='Escola do atendido', max_length=100, null=True)),
                ('tipo_escola', models.CharField(blank=True, choices=[('PÚBLICA', 'Pública'), ('PRIVADA', 'Privada')], help_text='Tipo de escola do atendido', max_length=50, null=True)),
                ('trabalho', models.BooleanField(default=False, help_text='O atendido trabalha?')),
                ('foto', models.ImageField(blank=True, help_text='Foto do atendido', null=True, upload_to='fotos_atendidos')),
                ('projeto_social', models.BooleanField(default=False, help_text='O atendido já participou de algum projeto social?')),
                ('convenio_medico', models.BooleanField(default=False, help_text='O atendido possui convênio médico?')),
                ('vacina_covid', models.BooleanField(default=False, help_text='O atendido tomou as vacinas contra a COVID-19?')),
                ('restricao_alimentar', models.TextField(blank=True, help_text='Restrições alimentares do atendido', null=True)),
                ('restricao_medica', models.TextField(blank=True, help_text='Restrições médicas do atendido', null=True)),
                ('medicacao_continua', models.TextField(blank=True, help_text='Medicação contínua do atendido', null=True)),
                ('deficiencia', models.TextField(blank=True, help_text='O Atendido possui alguma deficiência ou necessidade educacional especial?', null=True)),
                ('identidade_etnica', models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDÍGENA', 'Indígena'), ('NÃO DECLARADA', 'Não Declarada')], help_text='Identidade étnica do atendido', max_length=50, null=True)),
                ('numeracao_camisa', models.CharField(blank=True, help_text='Numeração da camisa do atendido', max_length=5, null=True)),
                ('numeracao_calca', models.CharField(blank=True, help_text='Numeração da calça do atendido', max_length=5, null=True)),
                ('numeracao_calcado', models.CharField(blank=True, help_text='Numeração do calçado do atendido', max_length=5, null=True)),
                ('termos_assinado', models.BooleanField(default=False, help_text='Os termos de: Ciencia do EDUC ; Dados/LGPD ; Uso de Imagem ; Saúde Bucal foram assinados?')),
                ('comissao_inclusiva', models.BooleanField(default=False, help_text='O Atendido tem necessidade de apoio da Comissão Inclusiva?')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True, help_text='Indica que o usuário será tratado como ativo. Ao invés de excluir atendidos, desmarque isso.')),
            ],
        ),
        migrations.CreateModel(
            name='AtendidoInclusivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.BooleanField(blank=True, help_text='O Atendido possui algum diagnóstico médico formal (laudo)?', null=True)),
                ('diagnostico_descricao', models.TextField(blank=True, help_text='Descrição do diagnóstico médico formal (laudo) do Atendido', null=True)),
                ('acompanhamento', models.BooleanField(blank=True, help_text='A condições de saúde requer acompanhamento ou suporte especializado? Exemplo: Transtorno do Espectro Autista, TDAH?', null=True)),
                ('recomendacoes', models.TextField(blank=True, help_text='Qual é a recomendação do profissional de saúde ou educacional para melhor atender o Atendido?', null=True)),
                ('comportamento_social', models.TextField(blank=True, help_text='Descreva o comportamento social do Atendido (interação com colegas, comunicação, etc.)', null=True)),
                ('dificuldades_aprendizado', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades específicas de aprendizado? Se sim, descreva.', null=True)),
                ('dificuldades_motoras', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades motoras? Se sim, descreva.', null=True)),
                ('dificuldade_atencao', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades de atenção ou concentração? Se sim, descreva.', null=True)),
                ('dificuldade_emocional', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades em controlar suas emoções ou comportamentais? Se sim, descreva.', null=True)),
                ('servicos_apoio', models.BooleanField(blank=True, help_text='O Atendido recebe algum serviço de apoio externo (terapia ocupacional, fonoaudiologia, psicologia, etc.)?', null=True)),
                ('expectativas_familia', models.TextField(blank=True, help_text='Quais são as expectativas da família em relação ao apoio inclusivo oferecido pelo projeto?', null=True)),
                ('observacoes_adicionais', models.TextField(blank=True, help_text='Adicione quaisquer outras informações relevantes sobre as necessidades inclusivas do Atendido.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome da família', max_length=50, null=True)),
                ('cep', models.CharField(blank=True, help_text='CEP da residência da família, somente números', max_length=10, null=True)),
                ('endereco', models.CharField(blank=True, help_text='Endereço da residência da família', max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, choices=[('NOVO HORIZONTE', 'Novo Horizonte'), ('JARDIM NOVO HORIZONTE', 'Jardim Novo Horizonte'), ('CECAP', 'CECAP'), ('CECAP ALTA', 'CECAP Alta'), ('BAIRRO DA CRUZ', 'Bairro da Cruz'), ('CAMPOS DOS IPES', 'Campos dos Ipes'), ('PARQUE DAS RODOVIAS', 'Parque das Rodovias'), ('VILA INDUSTRIAL', 'Vila Industrial'), ('VILA CRISTIANA', 'Vila Cristiana'), ('VILA PASSOS', 'Vila Passos'), ('VILA BRITO', 'Vila Brito'), ('VILA DELI', 'Vila Deli'), ('DONA ANA', 'Dona Ana'), ('SANTA LUCRÉCIA', 'Santa Lucrécia'), ('FAZENDA MONDEZIR', 'Fazenda Mondezir'), ('OUTRO BAIRRO', 'Outro Bairro')], help_text='Bairro da residência da família', max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, choices=[('LORENA', 'Lorena'), ('PIQUETE', 'Piquete'), ('GUARATINGUETÁ', 'Guaratinguetá'), ('CACHOEIRA PAULISTA', 'Cachoeira Paulista'), ('CANAS', 'Canas'), ('CRUZEIRO', 'Cruzeiro'), ('LAVRINHAS', 'Lavrinhas'), ('SÃO JOSÉ DOS CAMPOS', 'São José dos Campos'), ('TAUBATÉ', 'Taubaté'), ('OUTRA CIDADE', 'Outra Cidade')], help_text='Cidade da residência da família', max_length=100, null=True)),
                ('zona_residencial', models.CharField(blank=True, choices=[('ZONA RURAL', 'Zona Rural'), ('ZONA URBANA', 'Zona Urbana')], help_text='Zona residencial da residência da família', max_length=20, null=True)),
                ('situacao_moradia', models.CharField(blank=True, choices=[('PRÓPRIA QUITADA', 'Própria Quitada'), ('PRÓPRIA FINANCIADA', 'Própria Financiada'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('ABRIGO INSTITUCIONAL', 'Abrigo Institucional'), ('OUTRA SITUAÇÃO', 'Outra Situação')], help_text='Situação da moradia da família', max_length=100, null=True)),
                ('agua_encanada', models.BooleanField(default=False, help_text='A residência da família possui água encanada?')),
                ('esgoto_encanado', models.BooleanField(default=False, help_text='A residência da família possui esgoto encanado?')),
                ('energia_eletrica', models.BooleanField(default=False, help_text='A residência da família possui energia elétrica?')),
                ('renda_total_familia', models.CharField(blank=True, choices=[('MENOS DE 1000', 'menos de 1000'), ('ENTRE 1000-1500', 'Entre 1000 e 1500'), ('ENTRE 1500-2000', 'Entre 1500 e 2000'), ('ENTRE 2000-3000', 'Entre 2000 e 3000'), ('ENTRE 3000-4000', 'Entre 3000 e 4000'), ('ENTRE 4000-5000', 'Entre 4000 e 5000'), ('MAIS DE 5000', 'Mais de 5000')], help_text='Renda total da família', max_length=20, null=True)),
                ('pessoas_moram_familia', models.IntegerField(default=1, help_text='Número de pessoas que moram na residência da família')),
                ('pessoas_trabalham_familia', models.IntegerField(default=0, help_text='Número de pessoas que trabalham na residência da família')),
                ('programa_transferencia_renda', models.BooleanField(default=False, help_text='A família participa de algum programa de transferência de renda?')),
                ('internet_casa', models.BooleanField(default=False, help_text='A residência da família possui acesso à internet?')),
                ('comodos_casa', models.IntegerField(default=0, help_text='Número de cômodos na residência da família')),
                ('tv_casa', models.IntegerField(default=0, help_text='Número de televisores na residência da família')),
                ('banheiro_casa', models.IntegerField(default=0, help_text='Número de banheiros na residência da família')),
                ('motos_casa', models.IntegerField(default=0, help_text='Número de motos na residência da família')),
                ('carros_casa', models.IntegerField(default=0, help_text='Número de carros na residência da família')),
                ('geladeira_casa', models.IntegerField(default=0, help_text='Número de geladeiras na residência da família')),
                ('freezer_casa', models.IntegerField(default=0, help_text='Número de freezers na residência da família')),
                ('celular_casa', models.IntegerField(default=0, help_text='Número de celulares na residência da família')),
                ('computador_casa', models.IntegerField(default=0, help_text='Número de computadores na residência da família')),
                ('cesta_natal', models.BooleanField(default=False, help_text='A família recebeu cesta de Natal?')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Nome do responsável pelo atendido', max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, help_text='CPF do responsável pelo atendido, somente números', max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, help_text='RG do responsável pelo atendido, somente números', max_length=15, null=True)),
                ('parentesco', models.CharField(blank=True, choices=[('PAI', 'Pai'), ('MÃE', 'Mãe'), ('AVÔ', 'Avô'), ('AVÓ', 'Avó'), ('TIO', 'Tio'), ('TIA', 'Tia'), ('IRMÃO', 'Irmão'), ('IRMÃ', 'Irmã'), ('OUTRO', 'Outro')], help_text='Grau de parentesco com o atendido', max_length=50, null=True)),
                ('contato', models.CharField(blank=True, help_text='Número de contato do responsável pelo atendido, somente números', max_length=20, null=True)),
                ('outro_contato', models.CharField(blank=True, help_text='Número de contato alternativo do responsável pelo atendido, somente números', max_length=20, null=True)),
                ('trabalho', models.CharField(blank=True, help_text='Local de trabalho do responsável pelo atendido', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='E-mail do responsável pelo atendido', max_length=254, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], help_text='Escolaridade do responsável pelo atendido', max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PresencaAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=15)),
                ('atendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='atendido.atendido')),
            ],
        ),
    ]
