# Generated by Django 6.0 on 2025-12-19 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('responsavel', models.CharField(max_length=50)),
                ('sala', models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz')], max_length=20)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_atendidos')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
