# Generated by Django 4.2.27 on 2026-01-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabado', '0001_initial'),
        ('atendido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaatendido',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_atendidos', to='sabado.sabado'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendidos', to='atendido.familia'),
        ),
    ]
