# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sabado', '0001_initial'),
        ('atendido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaatendido',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_atendidos', to='sabado.sabado'),
        ),
    ]
