# Generated by Django 4.2.27 on 2025-12-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atendido", "0002_pai_alter_atendido_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendido",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendidos",
                to="atendido.pai",
            ),
        ),
    ]
