# Generated by Django 4.2.27 on 2026-02-14 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendido', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencaatendido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_registradas_atendidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendidoinclusivo',
            name='atendido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo', to='atendido.atendido'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Família que o atendido pertence, caso não tenha, cadastre uma nova família.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendidos', to='atendido.familia'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendido',
            name='responsavel',
            field=models.ManyToManyField(blank=True, help_text='Responsável(s) pelo atendido, caso não tenha, cadastre um novo responsável.', related_name='atendidos', to='atendido.responsavelatendido'),
        ),
    ]
