# Generated by Django 4.2.27 on 2026-02-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mudanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mudanca', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['mudanca'],
            },
        ),
        migrations.RemoveField(
            model_name='atendido',
            name='deficiencia',
        ),
        migrations.AddField(
            model_name='atendido',
            name='acompanhamento',
            field=models.CharField(blank=True, choices=[('NENHUM', 'Nenhum'), ('PEDIATRIA', 'Pediatria'), ('TERAPIA OCUPACIONAL', 'Terapia Ocupacional'), ('FONOAUDIOLOGIA', 'Fonoaudiologia'), ('PSICOLOGIA', 'Psicologia'), ('PSIQIATRA', 'Psiquiatria'), ('FISIOTERAPIA', 'Fisioterapia'), ('OUTRO ACOMPANHAMENTO', 'Outro Acompanhamento')], help_text='O atendido realiza acompanhamento com algum profissional? Se sim, qual?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='aprendizado',
            field=models.BooleanField(default=False, help_text='O atendido apresenta alguma dificuldade de aprendizado?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='campanha_vacinacao',
            field=models.BooleanField(default=False, help_text='Você apoiaria a realização de campanhas de vacinação para os atendidos do Projeto Criança Feliz?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='comportamento_regras',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('ÀS VEZES', 'Às vezes')], help_text='O atendido apresenta alguma dificuldade em seguir regras ou combinados?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='comportamento_social',
            field=models.CharField(blank=True, choices=[('INTERAGE BEM COM COLEGAS', 'Interage bem com colegas'), ('DIFICULDADE DE INTERAÇÃO SOCIAL', 'Dificuldade de interação social'), ('ISOLADO', 'Isolado'), ('AGRESSIVO', 'Agressivo'), ('TIMÍDO', 'Tímido'), ('DEPENDE DO AMBIENTE', 'Depende do ambiente'), ('AINDA ESTÁ SE ADAPTANDO', 'Ainda está se adaptando')], help_text='Como o atendido costuma se comportar em atividades em grupo e na socialização com outras pessoas da mesma idade?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='concentracao',
            field=models.BooleanField(default=False, help_text='O atendido apresenta dificuldade de concentração em atividades mais longas?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='diagnostico',
            field=models.BooleanField(default=False, help_text='O atendido possui algum diagnóstico, laudo ou acompanhamento relacionado ao desenvolvimento, aprendizagem ou comportamento (como TEA, TDAH, dificuldades de atenção, comunicação ou socialização)? Há condições de saúde que requerem acompanhamento ou suporte especializado?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='diagnostico_descricao',
            field=models.TextField(blank=True, help_text='Descrição do diagnóstico, laudo ou acompanhamento relacionado ao desenvolvimento, aprendizagem ou comportamento do atendido', null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='dificuldade_emocional',
            field=models.BooleanField(default=False, help_text='O atendido apresenta alguma dificuldade em controlar suas emoções ou comportamentos?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='dificuldade_emocional_descricao',
            field=models.TextField(blank=True, help_text='Descrição da dificuldade do atendido em controlar suas emoções ou comportamentos', null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='dificuldade_motora',
            field=models.BooleanField(default=False, help_text='O atendido apresenta alguma dificuldade motora ou de coordenação?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='dificuldade_motora_descricao',
            field=models.TextField(blank=True, help_text='Descrição da dificuldade motora ou de coordenação do atendido', null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='expectativas_familia',
            field=models.TextField(blank=True, help_text='Quais são as expectativas da família em relação ao apoio inclusivo oferecido pelo projeto?', null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='matricula',
            field=models.CharField(blank=True, choices=[('MATRÍCULA', 'Matrícula'), ('REMATRÍCULA', 'Rematrícula')], help_text='Indica se é matrícula ou rematrícula do atendido', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='mundacas_positivas',
            field=models.BooleanField(default=False, help_text='Desde que a criança participa do Projeto Criança Feliz, você percebeu mudanças positivas no comportamento dela?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='recomendacao_acompanhamento',
            field=models.TextField(blank=True, help_text='Qual é a recomendação do profissional de saúde ou educacional para melhor atender o atendido?', null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='saude_bucal',
            field=models.BooleanField(default=False, help_text='Antes de participar do Projeto Criança Feliz, o atendido já havia passado por atendimento odontológico?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='sensibilidade',
            field=models.BooleanField(default=False, help_text='O atendido apresenta sensibilidade a sons, luzes, cheiros ou toque?'),
        ),
        migrations.AddField(
            model_name='atendido',
            name='sensibilidade_descricao',
            field=models.TextField(blank=True, help_text='Descrição da sensibilidade do atendido a sons, luzes, cheiros ou toque', null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='impacto_social',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NÃO', 'Não'), ('ÀS VEZES', 'Às vezes')], help_text='O Projeto Criança Feliz contribui positivamente para a rotina da sua família?', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='tipo_impacto_social',
            field=models.CharField(blank=True, choices=[('APOIO NO DESENVOLVIMENTO DO ATENDIDO', 'Apoio no desenvolvimento do atendido'), ('SUPORTE À FAMÍLIA', 'Suporte à família'), ('ORIENTAÇÃO EDUCACIONAL', 'Orientação educacional'), ('CONTRIBUIÇÃO PARA ROTINA FAMILIAR', 'Contribuição para rotina familiar'), ('APOIO EMOCIONAL', 'Apoio emocional')], help_text='De que forma o Projeto Criança Feliz contribui positivamente na sua família?', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Adicione quaisquer outras informações relevantes sobre o atendido que não foram contempladas nos campos anteriores.', null=True),
        ),
    ]
