# Generated by Django 4.2.27 on 2026-01-21 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atendido', '0003_presencaatendido_registrado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('contato', models.CharField(blank=True, max_length=20, null=True)),
                ('outro_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('trabalho', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='familia',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='renda',
        ),
        migrations.AddField(
            model_name='atendido',
            name='contato',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='convenio_medico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='identidade_etnica',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='mae',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='medicacao_continua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='numeracao_calca',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='numeracao_calcado',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='numeracao_camisa',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='pai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='projeto_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendidos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendido',
            name='restricao_alimentar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='restricao_medica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='termos_assinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='vacina_covid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='agua_encanada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='banheiro_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='carros_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='celular_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='cesta_natal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='comodos_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='computador_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='energia_eletrica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='esgoto_encanado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='freezer_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='geladeira_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='internet_casa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='motos_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='pessoas_moram_familia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='familia',
            name='pessoas_trabalham_familia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familia',
            name='programa_transferencia_renda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='familia',
            name='renda_total_familia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='familia',
            name='situacao_moradia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='tv_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='responsavel',
            field=models.ManyToManyField(blank=True, related_name='atendidos', to='atendido.responsavelatendido'),
        ),
    ]
