# Generated by Django 4.2.27 on 2025-12-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atendido", "0003_alter_atendido_responsavel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atendido",
            name="responsavel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
