# Generated by Django 4.2.27 on 2026-01-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0004_responsavelatendido_remove_familia_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='ano_escolar',
            field=models.CharField(blank=True, choices=[('1º ANO', '1º Ano'), ('2º ANO', '2º Ano'), ('3º ANO', '3º Ano'), ('4º ANO', '4º Ano'), ('5º ANO', '5º Ano'), ('6º ANO', '6º Ano'), ('7º ANO', '7º Ano'), ('8º ANO', '8º Ano'), ('9º ANO', '9º Ano'), ('1ª SÉRIE DO ENSINO MÉDIO', '1ª Série do Ensino Médio'), ('2ª SÉRIE DO ENSINO MÉDIO', '2ª Série do Ensino Médio'), ('3ª SÉRIE DO ENSINO MÉDIO', '3ª Série do Ensino Médio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='comissao_inclusiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendido',
            name='escola',
            field=models.CharField(blank=True, choices=[('ESCOLA RUI BRASIL', 'Escola Rui Brasil'), ('ESCOLA ESTADUAL ARNOLFO AZEVEDO', 'Escola Estadual Arnolfo Azevedo'), ('E.M PROFª HERMÍNIA FIGUEIRA DE AZEVEDO ALMEIDA', 'E.M Profª Hermínia Figueira de Azevedo Almeida'), ('CEMEI JÂNIO QUADROS', 'CEMEI Jânio Quadros'), ('APARECIDA GUEDES', 'Aparecida Guedes'), ('ESCOLA GABRIEL PRESTES', 'Escola Gabriel Prestes'), ('E.M PROFESSORA LEDA MARIA BILARD DE CARVALHO', 'E.M Professora Leda Maria Bilard de Carvalho'), ('E.E PROF. LUIZ DE CASTRO PINTO', 'E.E Prof. Luiz de Castro Pinto'), ('E.E PROF. FRANCISCO MARQUES DE OLIVEIRA JUNIOR', 'E.E Prof. Francisco Marques de Oliveira Junior'), ('EE PEI PROF.ª MIQUELINA CARTOLANO', 'EE PEI Prof.ª Miquelina Cartolano'), ('ETEC PADRE CARLOS LEÔNCIO DA SILVA', 'Etec Padre Carlos Leôncio da Silva'), ('ESCOLA MARIA AUXILIADORA', 'Escola Maria Auxiliadora'), ('ESCOLA ESTADUAL LEONOR GUIMARÃES', 'Escola Estadual Leonor Guimarães'), ('OUTRO', 'Outro')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atendido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familia',
            name='zona_residencial',
            field=models.CharField(blank=True, choices=[('ZONA RURAL', 'Zona Rural'), ('ZONA URBANA', 'Zona Urbana')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='contato',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='convenio_medico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='identidade_etnica',
            field=models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDÍGENA', 'Indígena'), ('NÃO DECLARADA', 'Não Declarada')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='projeto_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='rg',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='trabalho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='familia',
            name='bairro',
            field=models.CharField(blank=True, choices=[('NOVO HORIZONTE', 'Novo Horizonte'), ('JARDIM NOVO HORIZONTE', 'Jardim Novo Horizonte'), ('CECAP', 'CECAP'), ('CECAP ALTA', 'CECAP Alta'), ('BAIRRO DA CRUZ', 'Bairro da Cruz'), ('CAMPOS DOS IPES', 'Campos dos Ipes'), ('PARQUE DAS RODOVIAS', 'Parque das Rodovias'), ('VILA INDUSTRIAL', 'Vila Industrial'), ('VILA CRISTIANA', 'Vila Cristiana'), ('VILA PASSOS', 'Vila Passos'), ('VILA BRITO', 'Vila Brito'), ('VILA DELI', 'Vila Deli'), ('DONA ANA', 'Dona Ana'), ('SANTA LUCRÉCIA', 'Santa Lucrécia'), ('FAZENDA MONDEZIR', 'Fazenda Mondezir'), ('OUTRO BAIRRO', 'Outro Bairro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cidade',
            field=models.CharField(blank=True, choices=[('LORENA', 'Lorena'), ('PIQUETE', 'Piquete'), ('GUARATINGUETÁ', 'Guaratinguetá'), ('CACHOEIRA PAULISTA', 'Cachoeira Paulista'), ('CANAS', 'Canas'), ('CRUZEIRO', 'Cruzeiro'), ('LAVRINHAS', 'Lavrinhas'), ('SÃO JOSÉ DOS CAMPOS', 'São José dos Campos'), ('TAUBATÉ', 'Taubaté'), ('OUTRA CIDADE', 'Outra Cidade')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='renda_total_familia',
            field=models.CharField(blank=True, choices=[('MENOS DE 1000', 'menos de 1000'), ('ENTRE 1000-1500', 'Entre 1000 e 1500'), ('ENTRE 1500-2000', 'Entre 1500 e 2000'), ('ENTRE 2000-3000', 'Entre 2000 e 3000'), ('ENTRE 3000-4000', 'Entre 3000 e 4000'), ('ENTRE 4000-5000', 'Entre 4000 e 5000'), ('MAIS DE 5000', 'Mais de 5000')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='situacao_moradia',
            field=models.CharField(blank=True, choices=[('PRÓPRIA QUITADA', 'Própria Quitada'), ('PRÓPRIA FINANCIADA', 'Própria Financiada'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('ABRIGO INSTITUCIONAL', 'Abrigo Institucional'), ('OUTRA SITUAÇÃO', 'Outra Situação')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('PAI', 'Pai'), ('MÃE', 'Mãe'), ('AVÔ', 'Avô'), ('AVÓ', 'Avó'), ('TIO', 'Tio'), ('TIA', 'Tia'), ('IRMÃO', 'Irmão'), ('IRMÃ', 'Irmã'), ('OUTRO', 'Outro')], max_length=50, null=True),
        ),
    ]
