# Generated by Django 4.2.27 on 2025-12-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("atendido", "0004_alter_atendido_responsavel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atendido",
            name="responsavel",
        ),
        migrations.AddField(
            model_name="atendido",
            name="pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atendidos",
                to="atendido.pai",
            ),
        ),
    ]
