# Generated by Django 4.2.27 on 2026-02-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0004_mudanca_remove_atendido_deficiencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendido',
            old_name='mundacas_positivas',
            new_name='mudancas_positivas',
        ),
        migrations.AddField(
            model_name='atendido',
            name='aspectos_mudancas',
            field=models.ManyToManyField(blank=True, help_text='Quais aspectos ou áreas de desenvolvimento você percebeu mudanças positivas na criança? (Marque todas as que se aplicam)', to='atendido.mudanca'),
        ),
    ]
