# Generated by Django 4.2.27 on 2026-01-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0005_atendido_ano_escolar_atendido_comissao_inclusiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica que o usuário será tratado como ativo. Ao invés de excluir atendidos, desmarque isso.'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='ano_escolar',
            field=models.CharField(blank=True, choices=[('1º ANO', '1º Ano'), ('2º ANO', '2º Ano'), ('3º ANO', '3º Ano'), ('4º ANO', '4º Ano'), ('5º ANO', '5º Ano'), ('6º ANO', '6º Ano'), ('7º ANO', '7º Ano'), ('8º ANO', '8º Ano'), ('9º ANO', '9º Ano'), ('1ª SÉRIE DO ENSINO MÉDIO', '1ª Série do Ensino Médio'), ('2ª SÉRIE DO ENSINO MÉDIO', '2ª Série do Ensino Médio'), ('3ª SÉRIE DO ENSINO MÉDIO', '3ª Série do Ensino Médio')], help_text='Ano escolar do atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='comissao_inclusiva',
            field=models.BooleanField(default=False, help_text='O Atendido tem necessidade de apoio da Comissão Inclusiva?'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='contato',
            field=models.CharField(blank=True, help_text='Número de contato do atendido, somente números', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='convenio_medico',
            field=models.BooleanField(default=False, help_text='O atendido possui convênio médico?'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do atendido, somente números', max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='data_nascimento',
            field=models.DateField(help_text='Data de nascimento do atendido'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='escola',
            field=models.CharField(blank=True, choices=[('ESCOLA RUI BRASIL', 'Escola Rui Brasil'), ('ESCOLA ESTADUAL ARNOLFO AZEVEDO', 'Escola Estadual Arnolfo Azevedo'), ('E.M PROFª HERMÍNIA FIGUEIRA DE AZEVEDO ALMEIDA', 'E.M Profª Hermínia Figueira de Azevedo Almeida'), ('CEMEI JÂNIO QUADROS', 'CEMEI Jânio Quadros'), ('APARECIDA GUEDES', 'Aparecida Guedes'), ('ESCOLA GABRIEL PRESTES', 'Escola Gabriel Prestes'), ('E.M PROFESSORA LEDA MARIA BILARD DE CARVALHO', 'E.M Professora Leda Maria Bilard de Carvalho'), ('E.E PROF. LUIZ DE CASTRO PINTO', 'E.E Prof. Luiz de Castro Pinto'), ('E.E PROF. FRANCISCO MARQUES DE OLIVEIRA JUNIOR', 'E.E Prof. Francisco Marques de Oliveira Junior'), ('EE PEI PROF.ª MIQUELINA CARTOLANO', 'EE PEI Prof.ª Miquelina Cartolano'), ('ETEC PADRE CARLOS LEÔNCIO DA SILVA', 'Etec Padre Carlos Leôncio da Silva'), ('ESCOLA MARIA AUXILIADORA', 'Escola Maria Auxiliadora'), ('ESCOLA ESTADUAL LEONOR GUIMARÃES', 'Escola Estadual Leonor Guimarães'), ('OUTRO', 'Outro')], help_text='Escola do atendido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], help_text='Escolaridade do atendido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do atendido', null=True, upload_to='fotos_atendidos'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='identidade_etnica',
            field=models.CharField(blank=True, choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDÍGENA', 'Indígena'), ('NÃO DECLARADA', 'Não Declarada')], help_text='Identidade étnica do atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='mae',
            field=models.CharField(blank=True, help_text='Nome da mãe do atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='medicacao_continua',
            field=models.TextField(blank=True, help_text='Medicação contínua do atendido', null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='nome',
            field=models.CharField(help_text='Nome completo do atendido', max_length=50),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='numeracao_calca',
            field=models.CharField(blank=True, help_text='Numeração da calça do atendido', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='numeracao_calcado',
            field=models.CharField(blank=True, help_text='Numeração do calçado do atendido', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='numeracao_camisa',
            field=models.CharField(blank=True, help_text='Numeração da camisa do atendido', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='pai',
            field=models.CharField(blank=True, help_text='Nome do pai do atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='projeto_social',
            field=models.BooleanField(default=False, help_text='O atendido já participou de algum projeto social?'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='restricao_alimentar',
            field=models.TextField(blank=True, help_text='Restrições alimentares do atendido', null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='restricao_medica',
            field=models.TextField(blank=True, help_text='Restrições médicas do atendido', null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do atendido, somente números', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='sala',
            field=models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz')], help_text='Sala em que o atendido está matriculado', max_length=20),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='termos_assinado',
            field=models.BooleanField(default=False, help_text='Os termos de: Ciencia do EDUC ; Dados/LGPD ; Uso de Imagem ; Saúde Bucal foram assinados?'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='trabalho',
            field=models.BooleanField(default=False, help_text='O atendido trabalha?'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='vacina_covid',
            field=models.BooleanField(default=False, help_text='O atendido tomou as vacinas contra a COVID-19?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='agua_encanada',
            field=models.BooleanField(default=False, help_text='A residência da família possui água encanada?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='bairro',
            field=models.CharField(blank=True, choices=[('NOVO HORIZONTE', 'Novo Horizonte'), ('JARDIM NOVO HORIZONTE', 'Jardim Novo Horizonte'), ('CECAP', 'CECAP'), ('CECAP ALTA', 'CECAP Alta'), ('BAIRRO DA CRUZ', 'Bairro da Cruz'), ('CAMPOS DOS IPES', 'Campos dos Ipes'), ('PARQUE DAS RODOVIAS', 'Parque das Rodovias'), ('VILA INDUSTRIAL', 'Vila Industrial'), ('VILA CRISTIANA', 'Vila Cristiana'), ('VILA PASSOS', 'Vila Passos'), ('VILA BRITO', 'Vila Brito'), ('VILA DELI', 'Vila Deli'), ('DONA ANA', 'Dona Ana'), ('SANTA LUCRÉCIA', 'Santa Lucrécia'), ('FAZENDA MONDEZIR', 'Fazenda Mondezir'), ('OUTRO BAIRRO', 'Outro Bairro')], help_text='Bairro da residência da família', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='banheiro_casa',
            field=models.IntegerField(default=0, help_text='Número de banheiros na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='carros_casa',
            field=models.IntegerField(default=0, help_text='Número de carros na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='celular_casa',
            field=models.IntegerField(default=0, help_text='Número de celulares na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP da residência da família, somente números', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cesta_natal',
            field=models.BooleanField(default=False, help_text='A família recebeu cesta de Natal?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='cidade',
            field=models.CharField(blank=True, choices=[('LORENA', 'Lorena'), ('PIQUETE', 'Piquete'), ('GUARATINGUETÁ', 'Guaratinguetá'), ('CACHOEIRA PAULISTA', 'Cachoeira Paulista'), ('CANAS', 'Canas'), ('CRUZEIRO', 'Cruzeiro'), ('LAVRINHAS', 'Lavrinhas'), ('SÃO JOSÉ DOS CAMPOS', 'São José dos Campos'), ('TAUBATÉ', 'Taubaté'), ('OUTRA CIDADE', 'Outra Cidade')], help_text='Cidade da residência da família', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='comodos_casa',
            field=models.IntegerField(default=0, help_text='Número de cômodos na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='computador_casa',
            field=models.IntegerField(default=0, help_text='Número de computadores na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço da residência da família', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='energia_eletrica',
            field=models.BooleanField(default=False, help_text='A residência da família possui energia elétrica?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='esgoto_encanado',
            field=models.BooleanField(default=False, help_text='A residência da família possui esgoto encanado?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='freezer_casa',
            field=models.IntegerField(default=0, help_text='Número de freezers na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='geladeira_casa',
            field=models.IntegerField(default=0, help_text='Número de geladeiras na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='internet_casa',
            field=models.BooleanField(default=False, help_text='A residência da família possui acesso à internet?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='motos_casa',
            field=models.IntegerField(default=0, help_text='Número de motos na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome da família', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='pessoas_moram_familia',
            field=models.IntegerField(default=1, help_text='Número de pessoas que moram na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='pessoas_trabalham_familia',
            field=models.IntegerField(default=0, help_text='Número de pessoas que trabalham na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='programa_transferencia_renda',
            field=models.BooleanField(default=False, help_text='A família participa de algum programa de transferência de renda?'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='renda_total_familia',
            field=models.CharField(blank=True, choices=[('MENOS DE 1000', 'menos de 1000'), ('ENTRE 1000-1500', 'Entre 1000 e 1500'), ('ENTRE 1500-2000', 'Entre 1500 e 2000'), ('ENTRE 2000-3000', 'Entre 2000 e 3000'), ('ENTRE 3000-4000', 'Entre 3000 e 4000'), ('ENTRE 4000-5000', 'Entre 4000 e 5000'), ('MAIS DE 5000', 'Mais de 5000')], help_text='Renda total da família', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='situacao_moradia',
            field=models.CharField(blank=True, choices=[('PRÓPRIA QUITADA', 'Própria Quitada'), ('PRÓPRIA FINANCIADA', 'Própria Financiada'), ('ALUGADA', 'Alugada'), ('CEDIDA', 'Cedida'), ('ABRIGO INSTITUCIONAL', 'Abrigo Institucional'), ('OUTRA SITUAÇÃO', 'Outra Situação')], help_text='Situação da moradia da família', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='tv_casa',
            field=models.IntegerField(default=0, help_text='Número de televisores na residência da família'),
        ),
        migrations.AlterField(
            model_name='familia',
            name='zona_residencial',
            field=models.CharField(blank=True, choices=[('ZONA RURAL', 'Zona Rural'), ('ZONA URBANA', 'Zona Urbana')], help_text='Zona residencial da residência da família', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='contato',
            field=models.CharField(blank=True, help_text='Número de contato do responsável pelo atendido, somente números', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do responsável pelo atendido, somente números', max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='email',
            field=models.EmailField(blank=True, help_text='E-mail do responsável pelo atendido', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('SEM ESCOLARIDADE', 'Sem Escolaridade'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental Incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental Completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio Incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio Completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior Incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior Completo'), ('PÓS-GRADUAÇÃO', 'Pós-Graduação')], help_text='Escolaridade do responsável pelo atendido', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome do responsável pelo atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='outro_contato',
            field=models.CharField(blank=True, help_text='Número de contato alternativo do responsável pelo atendido, somente números', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='parentesco',
            field=models.CharField(blank=True, choices=[('PAI', 'Pai'), ('MÃE', 'Mãe'), ('AVÔ', 'Avô'), ('AVÓ', 'Avó'), ('TIO', 'Tio'), ('TIA', 'Tia'), ('IRMÃO', 'Irmão'), ('IRMÃ', 'Irmã'), ('OUTRO', 'Outro')], help_text='Grau de parentesco com o atendido', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='rg',
            field=models.CharField(blank=True, help_text='RG do responsável pelo atendido, somente números', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='responsavelatendido',
            name='trabalho',
            field=models.CharField(blank=True, help_text='Local de trabalho do responsável pelo atendido', max_length=100, null=True),
        ),
    ]
