# Generated by Django 4.2.27 on 2026-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0005_rename_mundacas_positivas_atendido_mudancas_positivas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='cesta_natal',
            field=models.BooleanField(default=False, help_text='A família tem interesse em receber cesta de Natal?'),
        ),
    ]
