# Generated by Django 4.2.27 on 2025-12-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atendido", "0005_remove_atendido_responsavel_atendido_pai"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pai",
            new_name="Familia",
        ),
        migrations.RenameField(
            model_name="atendido",
            old_name="pai",
            new_name="familia",
        ),
    ]
