# Generated by Django 4.2.27 on 2025-12-30 23:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0006_rename_pai_familia_rename_pai_atendido_familia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaAtendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('atendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenca', to='atendido.atendido')),
            ],
        ),
    ]
