# Generated by Django 4.2.27 on 2026-01-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0006_atendido_ativo_alter_atendido_ano_escolar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='documento',
            field=models.FileField(blank=True, help_text='Documento do atendido (RG ou Certidão de Nascimento)', null=True, upload_to='documentos_atendidos'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='familia',
            field=models.ForeignKey(blank=True, help_text='Família que o atendido pertence, caso não tenha, cadastre uma nova família.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendidos', to='atendido.familia'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='responsavel',
            field=models.ManyToManyField(blank=True, help_text='Responsável(s) pelo atendido, caso não tenha, cadastre um novo responsável.', related_name='atendidos', to='atendido.responsavelatendido'),
        ),
        migrations.AlterField(
            model_name='atendido',
            name='sala',
            field=models.CharField(choices=[('VIOLETA', 'Violeta'), ('ANIL', 'Anil'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARELO', 'Amarelo'), ('LARANJA', 'Laranja'), ('VERMELHO', 'Vermelho'), ('FAMILIA_FELIZ', 'Família Feliz')], help_text='Sala em que o atendido está sendo matriculado', max_length=20),
        ),
    ]
