# Generated by Django 4.2.27 on 2026-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0006_alter_familia_cesta_natal'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='aspectos_outros',
            field=models.TextField(blank=True, help_text='Outros aspectos de mudança positiva que não se encaixam nas categorias acima', null=True),
        ),
    ]
