# Generated by Django 4.2.27 on 2026-01-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0007_atendido_documento_alter_atendido_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendido',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='atendido',
            name='pai',
        ),
    ]
