# Generated by Django 4.2.27 on 2026-01-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0008_remove_atendido_mae_remove_atendido_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='deficiencia',
            field=models.TextField(blank=True, help_text='O Atendido possui alguma deficiência ou necessidade educacional especial?', null=True),
        ),
    ]
