# Generated by Django 4.2.27 on 2025-12-31 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0008_alter_presencaatendido_atendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencaatendido',
            name='presente',
        ),
        migrations.AddField(
            model_name='presencaatendido',
            name='presenca',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADA', 'Falta Justificada')], default='PRESENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='presencaatendido',
            name='atendido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='atendido.atendido'),
        ),
    ]
