# Generated by Django 4.2.27 on 2026-01-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0009_atendido_deficiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendido',
            name='tipo_escola',
            field=models.CharField(blank=True, choices=[('PÚBLICA', 'Pública'), ('PRIVADA', 'Privada')], help_text='Tipo de escola do atendido', max_length=50, null=True),
        ),
    ]
