# Generated by Django 4.2.27 on 2026-01-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendido', '0010_atendido_tipo_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendidoInclusivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.BooleanField(blank=True, help_text='O Atendido possui algum diagnóstico médico formal (laudo)?', null=True)),
                ('diagnostico_descricao', models.TextField(blank=True, help_text='Descrição do diagnóstico médico formal (laudo) do Atendido', null=True)),
                ('acompanhamento', models.BooleanField(blank=True, help_text='A condições de saúde requer acompanhamento ou suporte especializado? Exemplo: Transtorno do Espectro Autista, TDAH?', null=True)),
                ('recomendacoes', models.TextField(blank=True, help_text='Qual é a recomendação do profissional de saúde ou educacional para melhor atender o Atendido?', null=True)),
                ('comportamento_social', models.TextField(blank=True, help_text='Descreva o comportamento social do Atendido (interação com colegas, comunicação, etc.)', null=True)),
                ('dificuldades_aprendizado', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades específicas de aprendizado? Se sim, descreva.', null=True)),
                ('dificuldades_motoras', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades motoras? Se sim, descreva.', null=True)),
                ('dificuldade_atencao', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades de atenção ou concentração? Se sim, descreva.', null=True)),
                ('dificuldade_emocional', models.TextField(blank=True, help_text='O Atendido apresenta dificuldades em controlar suas emoções ou comportamentais? Se sim, descreva.', null=True)),
                ('servicos_apoio', models.BooleanField(blank=True, help_text='O Atendido recebe algum serviço de apoio externo (terapia ocupacional, fonoaudiologia, psicologia, etc.)?', null=True)),
                ('expectativas_familia', models.TextField(blank=True, help_text='Quais são as expectativas da família em relação ao apoio inclusivo oferecido pelo projeto?', null=True)),
                ('observacoes_adicionais', models.TextField(blank=True, help_text='Adicione quaisquer outras informações relevantes sobre as necessidades inclusivas do Atendido.', null=True)),
                ('atendido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inclusivo', to='atendido.atendido')),
            ],
        ),
    ]
