# Generated by Django 4.2.27 on 2026-09-07 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gerenciamento.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerenciamento', '0006_simplifica_fluxo_e_multiplos_responsaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoMencaoPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='gerenciamento.comentariopauta')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_mencoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MaterialPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(blank=True, upload_to=gerenciamento.models.caminho_documento_pauta)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='gerenciamento.pauta')),
            ],
            options={
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificacaomencaopauta',
            constraint=models.UniqueConstraint(fields=('comentario', 'destinatario'), name='notificacao_unica_mencao_pauta'),
        ),
        migrations.AddConstraint(
            model_name='materialpauta',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('arquivo', ''), models.Q(('link', ''), _negated=True)), models.Q(models.Q(('arquivo', ''), _negated=True), ('link', '')), _connector='OR'), name='material_pauta_arquivo_ou_link'),
        ),
    ]
