# Generated by Django 4.2.27 on 2026-08-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_ok', models.DateTimeField(blank=True, null=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_push', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'inscrição push',
                'verbose_name_plural': 'inscrições push',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('mensagem', models.CharField(max_length=300)),
                ('destino', models.CharField(choices=[('TODOS', 'Todos os voluntários'), ('AREA', 'Por área')], max_length=10)),
                ('alvo', models.CharField(blank=True, help_text='Valor de LISTA_AREAS', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_enviado', models.PositiveIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
                'ordering': ('-criado_em',),
            },
        ),
    ]
