# Generated by Django 4.2.27 on 2026-08-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semanario', '0009_remove_material_unidade'),
        ('sabado', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='subtítulo')),
                ('periodo_inicio', models.DateField(verbose_name='início do período')),
                ('periodo_fim', models.DateField(verbose_name='fim do período')),
                ('texto_abertura', models.TextField(blank=True, verbose_name='carta de abertura')),
                ('texto_fechamento', models.TextField(blank=True, verbose_name='fechamento')),
                ('mostrar_numeros', models.BooleanField(default=True, verbose_name='mostrar os números do período')),
                ('mostrar_financeiro', models.BooleanField(default=True, verbose_name='mostrar onde o dinheiro foi aplicado')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADA', 'Publicada')], default='RASCUNHO', max_length=10)),
                ('token', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('link_publico_ativo', models.BooleanField(default=False, verbose_name='link público ativo')),
                ('link_expira_em', models.DateField(blank=True, null=True, verbose_name='link expira em')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'revista',
                'verbose_name_plural': 'revistas',
                'ordering': ['-periodo_fim', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SecaoRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(blank=True, max_length=20)),
                ('titulo', models.CharField(max_length=140, verbose_name='título')),
                ('texto', models.TextField(blank=True)),
                ('competencia', models.CharField(blank=True, max_length=120, verbose_name='competência')),
                ('foto_propria', models.ImageField(blank=True, null=True, upload_to='revista', verbose_name='foto')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('incluir', models.BooleanField(default=True, verbose_name='incluir na revista')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secoes_revista', to='semanario.atividade')),
                ('revista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='revista.revista')),
                ('sabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secoes_revista', to='sabado.sabado')),
            ],
            options={
                'verbose_name': 'seção da revista',
                'verbose_name_plural': 'seções da revista',
                'ordering': ['ordem', 'pk'],
            },
        ),
    ]
