# Generated by Django 4.2.27 on 2026-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='atividades_descartadas',
            field=models.JSONField(blank=True, default=list, help_text='Atividades que o CR tirou desta edição. Guardadas para que "remontar do semanário" não traga de volta o que ele já recusou.'),
        ),
    ]
